### ISSUE TITLE
Contains a Virus maybe ?

### ISSUE THREAD

**Issue by chedidkamal** [amakvana/YuzuModDownloader#1]
when I downloaded it, my Norton360 antivirus directly deleted it, so when I checked it on virustotal here are the results:
https://www.virustotal.com/gui/file/65768f1bbd0a30d43b28851f1030f3e6a6cb9b3833c3b26f578d8eccb668ffa6/detection
(something called MachineLearning/Anomalous.96% is considered malicious :/ )

**Comment by amakvana** [comment]
It's a false positive and contains nothing malicious whatsoever. MachineLearning/Anomalous is Malwarebytes’ generic detection name for files that are flagged by [Malwarebytes’ Machine Learning module](https://blog.malwarebytes.com/detections/machinelearning-anomalous-100/).

It's most likely flagged because the software downloads mods off the yuzu switch-wiki page and extracts them. However I can reassure you there is nothing malicious, as shown by all of the other antivirus engines returning negative on your upload.

**Comment by chedidkamal** [comment]
oh I understand
