### ISSUE TITLE
.dll file missing in download ?

### ISSUE THREAD

**Issue by xLuxSoldi3Rx** [amakvana/YuzuModDownloader#27]
**Describe the bug**
We tried, a few people, to download latest version and extracted all. We only get the .exe file. The .dll is missing. With the .exe only it downloads no mods. All Windows 11.

**To Reproduce**
1. Download your file and try it out.

**Expected behavior**
Getting the .dll file for downloading mods with your tool.

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 11
 - Yuzu Version latest official
 - Yuzu Installed

Thank you

**Comment by amakvana** [comment]
Hey! 

As of version 1.4.0.0, all of the necessary DLL files are packaged into the EXE. 

Would you be able to post your `qt-config.ini` file into here as an attachment?

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

Please reach out if you have or find the answers we need so that we can investigate further.
