### ISSUE TITLE
Mods download to load game folders, but do not unzip

### ISSUE THREAD

**Issue by tapperp** [amakvana/YuzuModDownloader#6]
Amakvana, thank you for this much appreciated utility!

The problem I have noticed is that mods are downloaded correctly to the load game folders, but are not actually being unzipped. I have to manually find each game folder and unzip the mod files. 

When yuzumoddownloader is running, it says it is unzipping the mods but they are not actually unzipped. 

Please advise if I am missing some step for correct usage. Thank you.

**Comment by amakvana** [comment]
Not too sure, I've ran it just now and they unzip just fine? As of now, YMD does not delete the zips that have been downloaded (that will be rectified soon).

If you move all the contents within the ```load``` folder elsewhere, open yuzu, close yuzu then rerun YMD, all of the mods will redownload.

Any game in particular which isn't downloading?

**Comment by maxens-wlfr** [comment]
I've had this problem too with Smash Bros.
Moving them elsewhere then retrying does the same thing again

**Comment by Woozellin** [comment]
Oops! Just realized this issue was brought up before!

@tapperp @maxens-wlfr 
By any chance, does your <user> folder have a space in it?  ie C:\users\<user folder>
My user folder has a space in it and we found that was the culprit.

Please check the discussion I had with @amakvana here:  (includes updated YuzuModDownloader.exe)
https://github.com/amakvana/YuzuModDownloader/issues/12

Hope that helps!

**Comment by amakvana** [comment]
Closed - Fixed in v1.1.0.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
